### ISSUE TITLE
Include count of number of genes detected

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/vfb-scRNAseq-ontology#14]
Not sure whether this can be done easily here or downstream using cypher.  If latter, this query works:

```
MATCH (gene:Gene)<-[:expresses]-(clu:Cluster)-[:has_source]->(ds:DataSet)
WITH ds, apoc.coll.toSet(COLLECT(gene)) AS genes 
RETURN ds.label as dataset, size(genes) AS depth order by depth DESC
```

Think high priority to get this in and to expose through API.  Users need a way to choose the highest seq depth dataset available for their cell type as it makes a big difference to the results.

**Comment by Clare72** [comment]
Yes, can be done here. Do we want number of genes for any extent (pre-filtering) or just extent >0.2 (post-filtering). If post-filtering, it might be easier to do in cypher (but impossible to do in cypher for pre-filtering numbers).

**Comment by dosumis** [comment]
> Do we want number of genes for any extent (pre-filtering) or just extent >0.2 (post-filtering).

Good point.  I think post filtering is what's needed to inform queries, but might be useful to have both.

**Comment by Clare72** [comment]
gene counts added to clusters and datasets - now in files in e809bf3da74116088631f33708406240b7212f0a
need to update vfb-connect to use these - see https://github.com/VirtualFlyBrain/VFB_connect/issues/224
