### ISSUE TITLE
Add xref to scAtlas on DataSet.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/vfb-scRNAseq-ontology#2]
Damian to check this can be found in FlyBase and point to where.

**Comment by Clare72** [comment]
https://github.com/VirtualFlyBrain/vfb-scRNAseq-ontology/pull/3/commits/68a2c9c24307d9619fc383334bb24adc8c9c019b
https://github.com/VirtualFlyBrain/vfb-scRNAseq-ontology/pull/3/commits/eda4250a401adcc7931390821e34fb56213be7a1

still needs site node adding to VFB

**Comment by dosumis** [comment]
Please check if we have a method for site nice addition on KB_tools.  If not, please co-ord with @Robbie1977 to add.

**Comment by Clare72** [comment]
site node added to KB
`MATCH (n:Site {label:"EMBL-EBI Single Cell Expression Atlas"}) RETURN n`
