### ISSUE TITLE
Reduce extent cutoff 

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/vfb-scRNAseq-ontology#9]
I'm increasingly finding evidence that suggests the 0.5 extent cutoff is too high.

e.g.  querying for well known acetylcholine biosynthetic or transporter genes (SLC22A, CHAT OR ChT) only supports 50/170 cholinergic neuron types.

If eliminating  completely would blow up the DB too much (presumably there is a long tail of very low extent expression just as there is of monosynaptic connections), I think best to go for something very low.   Maybe 0.05?

**Comment by Clare72** [comment]
expression data now using 0.05 extent cutoff - since https://github.com/VirtualFlyBrain/vfb-scRNAseq-ontology/commit/ff16bdf5ed79ddd927f202f78dfc610f80b18317

**Comment by Clare72** [comment]
![Figure_1](https://github.com/VirtualFlyBrain/vfb-scRNAseq-ontology/assets/38460997/2aaaa14b-753e-4899-a0e1-c19c9aef9112)

**Comment by Clare72** [comment]
0.05 currently giving 6,910,295 data points
0.5 was 850,535

**Comment by Clare72** [comment]
data point being unique cluster + gene combination

**Comment by Clare72** [comment]
0.1 -> 4,632,372
0.2 -> 2,713,871

**Comment by Robbie1977** [comment]
So if we can move to 0.2 for now

**Comment by Clare72** [comment]
closing this for now - reopen if/when change is required (now at 0.2)
